### ISSUE TITLE
cant find the "PatchZone.GUI.exe"

### ISSUE THREAD

**Issue by SolusVagus4544** [InflexCZE/PatchZone#4]
Ive Searched the downloaded file. an searched on your github an i still cant find it........

**Comment by InflexCZE** [comment]
When you navigate to Releases and click on latest release you should get here:
https://github.com/InflexCZE/PatchZone/releases/tag/v0.1.2-alpha

Then click on "Assets" and download `PatchZone.zip`
The `PatchZone.GUI.exe` is in `PatchZone` sub-folder of the archive. 

Note that PatchZone binaries are not signed with any certificate so some antiviruses may be sensitive to that.
If `exe`s get deleted suspiciously upon extraction try pausing your antivirus for a sec to address that.
PatchZone is open source so no malware included 😃
